---
- hosts: localhost:DVT:CE
  gather_facts: no
  tasks:
  - set_fact: 
      testcase: BASELINE CONFIGURATION
      test_dir: "testcase/0.BASELINE"
      cacheable: yes

- name: Create Directories
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create directories      
    file: 
      path: "{{playbook_dir}}/{{item}}" 
      state: directory
    with_items:
      - "{{test_dir}}"

- name: "Gathering Baseline Configuration"
  hosts: [ DVT, CE ]
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:

  - name: Retrieving the {{testcase}} in regular curly braces format
    juniper_junos_config:
      retrieve: 'committed'
      diff: true
      check: false
      commit: false
      dest_dir: "{{playbook_dir}}/{{test_dir}}"

  - name: Retrieving the {{testcase}} in 'set' format
    juniper_junos_config:
      retrieve: 'committed'
      diff: true
      check: false
      commit: false
      format: 'set'
      dest_dir: "{{playbook_dir}}/{{test_dir}}"