---
- name: Test Case 1-4 - Convergence Test - SPINE Link Failure
  hosts: localhost
  gather_facts: no

  tasks:

  - name: Create directories      
    file: 
      path: "{{playbook_dir}}/testcase/1.4/1" 
      state: directory
    
- name: "{{testcase}}"
  hosts: S-DC1-1
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars:
    testcase: "Test Case 1-4: Step 1 - Bringing down interface ae3 on S-DC1-1 (laser off)"
    test_dir: "testcase/1.4/1"

  tasks:

  - name: Gathering regular output for {{testcase}}
    juniper_junos_command:
      command:
        - "show interfaces ae3 descriptions"
        - "show lacp interfaces ae3"
        - 'request pfe execute target fpc0 command "show qsfp list"'
        - 'request pfe execute target fpc0 command "test qsfp 10 laser off"'
      dest_dir: "{{playbook_dir}}/{{test_dir}}/"
