---
- hosts: localhost:S-DC1-1
  gather_facts: no
  tasks:
  - set_fact: 
      test_dir: "testcase/1.4/1"
      cacheable: yes

- hosts: localhost
  gather_facts: no
  tasks:
  - file: 
      path: "{{playbook_dir}}/{{test_dir}}" 
      state: directory

- name: "Test Case 1-4: 5th attempt - Bringing down interface ae3 on S-DC1-1 (laser off)"
  hosts: S-DC1-1
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  tasks:
  - name: Bringing down interface
    juniper_junos_command:
      command:
        - 'show interfaces ae3 descriptions'
        - 'show lacp interfaces ae3'
        - 'request pfe execute target fpc0 command "show qsfp list"'
        - 'request pfe execute target fpc0 command "test qsfp 10 laser off"'
        - 'show interfaces ae3 terse'
      dest_dir: "{{playbook_dir}}/{{test_dir}}/"
    register: response
    
  - name: Print the coutput.
    debug:
      var: response