---
- name: Test Case1-6 - Convergence Test - SPINE Link Failure
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create directories      
    file: 
      path: "{{playbook_dir}}/testcase/1.6/0" 
      state: directory

- name: "{{testcase}}"
  hosts: LEAF
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars:
    testcase: "Test Case1-6: Step 0 - Baseline on LEAF routers"
    test_dir: "testcase/1.6/0"
  tasks:

  - name: Gathering regular output for {{testcase}}
    juniper_junos_command:
      command:
        - "show configuration routing-instances vlan30"
        - "show configuration routing-instances vrf30"
        - "show interfaces ae10.30 terse"
        - "show interfaces irb.30 terse"
        - "show bgp summary"
        - "show route advertising-protocol bgp 10.35.1.1 table vrf30"
        - "show route receive-protocol bgp 10.35.1.1 table vrf30"
        - "show route advertising-protocol bgp 10.35.1.2 table vrf30"
        - "show route receive-protocol bgp 10.35.1.2 table vrf30"
        - "show route table vrf30 match-prefix 5:*"
      dest_dir: "{{playbook_dir}}/{{test_dir}}/"
      return_output: false

  - name: Gathering output for VPN routes
    juniper_junos_command:
      command:
        - "show route 10.30.0/24"
        - "show route 300::/64"
      dest: "{{playbook_dir}}/{{test_dir}}/{{ inventory_hostname }}_show_route.txt"
      return_output: false

- name: "{{testcase}}"
  hosts: SPINE
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars:
    testcase: "Test Case1-6: Step 0 - Baseline on SPINE routers"
    test_dir: "testcase/1.6/0"

  tasks:

  - name: Gathering output for {{testcase}}
    juniper_junos_command:
      command:
        - "show configuration routing-instances vlan30"
        - "show configuration routing-instances vrf30"
        - "show interfaces ae10.30 terse"
        - "show interfaces irb.30 terse"
        - "show bgp summary"
        - "show route advertising-protocol bgp 10.35.1.3 table vrf30"
        - "show route receive-protocol bgp 10.35.1.3 table vrf30"
        - "show route advertising-protocol bgp 10.35.1.4 table vrf30"
        - "show route receive-protocol bgp 10.35.1.4 table vrf30"
        - "show route advertising-protocol bgp 10.35.2.3 table vrf30"
        - "show route receive-protocol bgp 10.35.2.3 table vrf30"
        - "show route advertising-protocol bgp 10.35.2.4 table vrf30"
        - "show route receive-protocol bgp 10.35.2.4 table vrf30"
        - "show route table vrf30 match-prefix 5:*"
      dest_dir: "{{playbook_dir}}/{{test_dir}}/"
      return_output: false

  - name: Gathering output for VPN routes
    juniper_junos_command:
      command:
        - "show route 10.30.0/24"
        - "show route 300::/64"
      dest: "{{playbook_dir}}/{{test_dir}}/{{ inventory_hostname }}_show_route.txt"
      return_output: false