---
- hosts: localhost:LEAF:SPINE
  gather_facts: no
  tasks:
  - set_fact: 
      testcase: 1-5-STEADY-EVI30-TYPE5
      config: type5-evi30
      test_dir: "testcase/1.5-STEADY-EVI30-TYPE5"
      cacheable: yes
  
    
- name: Create directories
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create directories      
    file: 
      path: "{{playbook_dir}}/{{test_dir}}" 
      state: directory

- name: "{{testcase}}"
  hosts: LEAF
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  tasks:

  - name: Gathering regular output for {{testcase}}
    juniper_junos_command:
      command:
        - "show configuration routing-instances vlan30"
        - "show configuration routing-instances vrf30"
        - "show configuration protocols bgp"
        - "show configuration policy-options policy-statement PL-EVI30-T5-V4-SLASH-32"
        - "show configuration policy-options policy-statement PL-EVI30-T5-V6-SLASH-64"
        - "show interfaces ae10.30 terse"
        - "show interfaces irb.30 terse"
        - "show bgp summary instance vrf30"
        - "show route summary table bgp"
        - "show route advertising-protocol bgp 10.35.1.1 table vrf30"
        - "show route receive-protocol bgp 10.35.1.1 table vrf30"
        - "show route advertising-protocol bgp 10.35.1.2 table vrf30"
        - "show route receive-protocol bgp 10.35.1.2 table vrf30"
        - "show route table vrf30 match-prefix 5:*"
      dest_dir: "{{playbook_dir}}/{{test_dir}}/"
      return_output: false

  - name: Gathering output for VPN routes
    juniper_junos_command:
      command:
        - "show route 10.30.0/24"
        - "show route 300::/64"
      dest: "{{playbook_dir}}/{{test_dir}}/{{ inventory_hostname }}_show_route.txt"
      return_output: false

- name: "{{testcase}}"
  hosts: SPINE
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  tasks:

  - name: Gathering output for {{testcase}}
    juniper_junos_command:
      command:
        - "show bgp summary instance vrf30"
        - "show route advertising-protocol bgp 10.35.1.3 table vrf30"
        - "show route receive-protocol bgp 10.35.1.3 table vrf30"
        - "show route advertising-protocol bgp 10.35.1.4 table vrf30"
        - "show route receive-protocol bgp 10.35.1.4 table vrf30"
        - "show route advertising-protocol bgp 10.35.2.3 table vrf30"
        - "show route receive-protocol bgp 10.35.2.3 table vrf30"
        - "show route advertising-protocol bgp 10.35.2.4 table vrf30"
        - "show route receive-protocol bgp 10.35.2.4 table vrf30"
        - "show route table vrf30 match-prefix 5:*"
      dest_dir: "{{playbook_dir}}/{{test_dir}}/"
      return_output: false

  - name: Gathering output for VPN routes
    juniper_junos_command:
      command:
        - "show route 10.30.0/24"
        - "show route 300::/64"
      dest: "{{playbook_dir}}/{{test_dir}}/{{ inventory_hostname }}_show_route.txt"
      return_output: false