---
- hosts: localhost:S-DC1-1
  gather_facts: no
  tasks:
  - set_fact: 
      testcase: 'Test Case 2-2 LF-CONVERG-EVI30-VRF'
      cacheable: yes
  
- name: "{{testcase|upper}} - 5th attempt - Restoring interface ae3 on S-DC1-1 (laser off)"
  hosts: S-DC1-1
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  tasks:
  - name: Bringing up interface
    juniper_junos_command:
      command:
        - 'request pfe execute target fpc0 command "test qsfp 10 laser on"'
    register: response
    
  - name: Print the coutput.
    debug:
      var: response