---
- name: Test Case 2-1 STEADY-EVPN-VRF-EVI30
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create directories      
    file: 
      path: "{{playbook_dir}}/testcase/2.1/0" 
      state: directory

- name: "{{testcase}}"
  hosts: LEAF
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars:
    testcase: "Test Case 2-1: Baseline on LEAF routers"
    test_dir: "testcase/2.1/0"

  tasks:

  - name: Gathering regular output for {{testcase}}
    juniper_junos_command:
      command:
        - "show configuration routing-instances vlan30"
        - "show configuration routing-instances vrf30"
        - "show interfaces ae10.30 terse"
        - "show interfaces irb.30 terse"
        - "show interfaces ae0 statistics"
        - "show interfaces ae1 statistics"
        - "show interfaces ae10.30 statistics"
      dest_dir: "{{playbook_dir}}/{{test_dir}}/"
      return_output: false

- name: "{{testcase}}"
  hosts: SPINE
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars:
    testcase: "Test Case 2-1: Step 0 - Baseline on SPINE routers"
    test_dir: "testcase/2.1/0"

  tasks:

  - name: Gathering output for {{testcase}}
    juniper_junos_command:
      command:
        - "show interfaces descriptions"
        - "show interfaces ae3 statistics"
        - "show interfaces ae4 statistics"
        - "show interfaces ae0 statistics"
        - "show interfaces ae1 statistics"
        - "show interfaces ae2 statistics"
      dest_dir: "{{playbook_dir}}/{{test_dir}}/"
      return_output: false
