---
- name: "Test Case 3-2: Convergence Test - SPINE Link Failure"
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create directories      
    file: 
      path: "{{playbook_dir}}/testcase/3.2/0" 
      state: directory

- name: "{{testcase}}"
  hosts: LEAF
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars:
    testcase: "Test Case 3-2: Step 0 - Baseline on LEAF routers"
    test_dir: "testcase/3.2/0"
  tasks:

  - name: Gathering regular output for {{testcase}}
    juniper_junos_command:
      command:
        - "show configuration routing-instances vlan10"
        - "show configuration routing-instances vrf10"
        - "show interfaces ae10.10 terse"
        - "show interfaces irb.10 terse"
        - "show bgp summary"
        - "show route advertising-protocol bgp 10.35.1.1 table vrf10"
        - "show route receive-protocol bgp 10.35.1.1 table vrf10"
        - "show route advertising-protocol bgp 10.35.1.2 table vrf10"
        - "show route receive-protocol bgp 10.35.1.2 table vrf10"
        - "show route table vrf10 match-prefix 5:*"
        - "show configuration routing-instances vlan20"
        - "show configuration routing-instances vrf20"
        - "show interfaces ae10.20 terse"
        - "show interfaces irb.20 terse"
        - "show bgp summary"
        - "show route advertising-protocol bgp 10.35.1.1 table vrf20"
        - "show route receive-protocol bgp 10.35.1.1 table vrf20"
        - "show route advertising-protocol bgp 10.35.1.2 table vrf20"
        - "show route receive-protocol bgp 10.35.1.2 table vrf20"
        - "show route table vrf20 match-prefix 5:*"
      dest_dir: "{{playbook_dir}}/{{test_dir}}/"
      return_output: false

  - name: Gathering output for VPN routes
    juniper_junos_command:
      command:
        - "show route 10.10.0/24"
        - "show route 10.10.10/24"
        - "show route 10.20.0/24"
        - "show route 10.20.20/24"
        - "show route 100::/64"
        - "show route 110::/64"
        - "show route 200::/64"
        - "show route 220::/64"
      dest: "{{playbook_dir}}/{{test_dir}}/{{ inventory_hostname }}_show_route.txt"
      return_output: false

- name: "{{testcase}}"
  hosts: SPINE
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars:
    testcase: "Test Case 3-2: Step 0 - Baseline on SPINE routers"
    test_dir: "testcase/3.2/0"

  tasks:

  - name: Gathering output for {{testcase}}
    juniper_junos_command:
      command:
        - "show configuration routing-instances vlan10"
        - "show configuration routing-instances vrf10"
        - "show interfaces ae10.10 terse"
        - "show interfaces irb.10 terse"
        - "show bgp summary"
        - "show route advertising-protocol bgp 10.35.1.3 table vrf10"
        - "show route receive-protocol bgp 10.35.1.3 table vrf10"
        - "show route advertising-protocol bgp 10.35.1.4 table vrf10"
        - "show route receive-protocol bgp 10.35.1.4 table vrf10"
        - "show route advertising-protocol bgp 10.35.3.2 table vrf10"
        - "show route receive-protocol bgp 10.35.3.2 table vrf10"
        - "show route advertising-protocol bgp 10.35.2.4 table vrf10"
        - "show route receive-protocol bgp 10.35.2.4 table vrf10"
        - "show route table vrf10 match-prefix 5:*"
        - "show configuration routing-instances vlan20"
        - "show configuration routing-instances vrf20"
        - "show interfaces ae10.20 terse"
        - "show interfaces irb.20 terse"
        - "show bgp summary"
        - "show route advertising-protocol bgp 10.35.1.3 table vrf20"
        - "show route receive-protocol bgp 10.35.1.3 table vrf20"
        - "show route advertising-protocol bgp 10.35.1.4 table vrf20"
        - "show route receive-protocol bgp 10.35.1.4 table vrf20"
        - "show route advertising-protocol bgp 10.35.3.2 table vrf20"
        - "show route receive-protocol bgp 10.35.3.2 table vrf20"
        - "show route advertising-protocol bgp 10.35.2.4 table vrf20"
        - "show route receive-protocol bgp 10.35.2.4 table vrf20"
        - "show route table vrf20 match-prefix 5:*"
      dest_dir: "{{playbook_dir}}/{{test_dir}}/"
      return_output: false

  - name: Gathering output for VPN routes
    juniper_junos_command:
      command:
        - "show route 10.10.0/24"
        - "show route 10.10.10/24"
        - "show route 10.20.0/24"
        - "show route 10.20.20/24"
        - "show route 100::/64"
        - "show route 110::/64"
        - "show route 200::/64"
        - "show route 220::/64"
      dest: "{{playbook_dir}}/{{test_dir}}/{{ inventory_hostname }}_show_route.txt"
      return_output: false