---
  - name: Clean up the configuration
    import_playbook: pb-wipe-all.yml

  - name: Deploy Fabric configuration
    import_playbook: pb-build-fabric.yml

  - name: Deploy EVI 10 configuration
    import_playbook: pb-build-type5-evi10.yml

  - name: Deploy EVI 20 configuration
    import_playbook: pb-build-type5-evi20.yml