---
- name: Checking for Junos images under /var/tmp/
  hosts: S-DC1
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars:
    credentials:
      host: "{{ inventory_hostname }}"

  tasks:

  - name: Checking NETCONF connectivity
    wait_for: 
      host: "{{ inventory_hostname }}"
      port: "{{ ansible_port }}"
      timeout: 2
    register: netconf_result

  - name: Checking for Junos images under /var/tmp/  
    when: netconf_result|success
    juniper_junos_command:
      command:
        - 'file list  re0:/var/tmp/junos-vmhost*'
        - 'file list  re1:/var/tmp/junos-vmhost*'
    register: response
    
  - name: Print the output.
    debug:
      var: response

  
