---
- name: 1- Create Directories
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create directories
    file: 
      path: "{{playbook_dir}}/{{ item }}" 
      state: directory
    with_items: 
     - config
     - diff
    
- name: 2- SPINE & LEAF MX routers
  hosts: DVT
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars:
    config: wipe-all
  tasks:

  - name: Building {{config|upper}} configurations for SPINE & LEAF MX routers
    vars:
      config: wipe-all
      junos_jinja_template: "{{playbook_dir}}/templates/{{config}}.j2"
    template: 
      src: "{{junos_jinja_template}}"
      dest: "{{playbook_dir}}/config/{{ inventory_hostname }}.{{config}}.conf"

  - name: Install Generated {{config|upper}} Configurations
    juniper_junos_config:
      config_mode: 'private'
      load: 'replace'
      src: "{{playbook_dir}}/config/{{ inventory_hostname }}.{{config}}.conf"
      comment: "Deploying {{config|upper}} configuration"
      diff: yes
      diffs_file: "{{playbook_dir}}/diff/{{ inventory_hostname }}.{{config}}.log"
    register: response
  
  - name: Print the config changes.
    debug:
      var: response.diff_lines
