host_name: L-DC1-1B
fxp0: 192.168.200.72
loopback: 10.35.1.4
iso: 49.0001.0100.3500.1004.00
local_asn: 64514
spring_ipv4_index: 1004
spring_ipv6_index: 61004
neighbors:
  - interface: ae0
    ae_members:
    - xe-0/1/0:0
    name: S-DC1-1
    type: leaf
    asn: 64514
    peer_loopback: 10.35.1.1
    peer_ip: 10.35.11.2
    local_ip: 10.35.11.3
  - interface: ae1
    ae_members:
     - xe-0/1/1:0
    name: S-DC1-2
    type: leaf
    asn: 64514
    peer_loopback: 10.35.1.2
    peer_ip: 10.35.12.2
    local_ip: 10.35.12.3