host_name: S-DC1-2
fxp0: 192.168.200.60
loopback: 10.35.1.2
iso: 49.0001.0100.3500.1002.00
local_asn: 64514
spring_ipv4_index: 1002
spring_ipv6_index: 61002
neighbors:
  - interface: ae0
    ae_members:
    - xe-0/1/0:0
    name: S-DC2-1
    type: spine
    peer_loopback: 10.35.2.1
    peer_ip: 10.35.0.7
    local_ip: 10.35.0.6
  - interface: ae1
    ae_members:
     - xe-0/1/1:0
    name: S-DC2-2
    type: spine
    peer_loopback: 10.35.2.2
    peer_ip: 10.35.0.9
    local_ip: 10.35.0.8
  - interface: ae2
    ae_members:
     - xe-0/1/2:0
    name: S-DC1-1
    type: spine
    peer_loopback: 10.35.1.1
    peer_ip: 10.35.0.4
    local_ip: 10.35.0.5
  - interface: ae3
    ae_members:
     - xe-0/1/3:0
    name: L-DC1-1A
    type: leaf
    asn: 64514
    peer_loopback: 10.35.1.3
    peer_ip: 10.35.12.1
    local_ip: 10.35.12.0
  - interface: ae4
    ae_members:
     - xe-0/1/4:0
    type: leaf
    name: L-DC1-1B
    peer_loopback: 10.35.1.4
    peer_ip: 10.35.12.3
    local_ip: 10.35.12.2