---
  - hosts: localhost:DVT
    gather_facts: no
    tasks:
    - set_fact: 
        testcase: 2-2-NF-CONVERG-EVI30-L3VPN
        test_dir: "testcase/2-2-NF-CONVERG-EVI30-L3VPN/2"
        cacheable: yes
      
  - name: Create directories
    hosts: localhost
    gather_facts: no
    tasks:
    - name: Create directories      
      file: 
        path: "{{playbook_dir}}/{{test_dir}}" 
        state: directory
  
  - name: Verification for EVI 30
    hosts: SPINE
    roles:
      - Juniper.junos
    connection: local
    gather_facts: no
    tasks:
    - name: Gathering regular output for {{testcase}}
      juniper_junos_command:
        command:
          - 'set cli timestamp'
          - "show configuration routing-instances vlan30"
          - "show configuration routing-instances vrf30"
          - 'show bfd session'
          - 'show isis interface'
          - 'show isis adjacency'
          - 'show bgp summary'
          - "show interfaces ae10 statistics"
          - "show interfaces ae0 statistics"
          - "show interfaces ae1 statistics"
          - "show interfaces ae2 statistics"
          - "show interfaces ae3 statistics"
          - "show interfaces ae4 statistics"
        dest_dir: "{{playbook_dir}}/{{test_dir}}/"
        return_output: false
  
  - name: Verification for EVI 30
    hosts: LEAF
    roles:
      - Juniper.junos
    connection: local
    gather_facts: no
    tasks:
    - name: Gathering regular output for {{testcase}}
      juniper_junos_command:
        command:
          - 'set cli timestamp'
          - "show configuration routing-instances vlan30"
          - "show configuration routing-instances vrf30"
          - 'show bfd session'
          - 'show isis interface'
          - 'show isis adjacency'
          - 'show bgp summary'
          - "show interfaces ae10 statistics"
          - "show interfaces ae0 statistics"
          - "show interfaces ae1 statistics"
        dest_dir: "{{playbook_dir}}/{{test_dir}}/"
        return_output: false

