---
  - hosts: localhost:S-DC1-1
    gather_facts: no
    tasks:
    - set_fact: 
        testcase: 4-1-LF-CONVERG-EVI10-20-SRX-L3VPN
        test_dir: "testcase/4-1-LF-CONVERG-EVI10-20-SRX-L3VPN/6/UP"
        cacheable: yes
  
  - hosts: localhost
    gather_facts: no
    tasks:
    - file: 
        path: "{{playbook_dir}}/{{test_dir}}" 
        state: directory
  
  - name: Bringing up interface ae3 on S-DC1-1 (laser on)
    hosts: S-DC1-1
    roles:
      - Juniper.junos
    connection: local
    gather_facts: no
    tasks:
    - name: Bringing up interface
      juniper_junos_command:
        command:
          - 'set cli timestamp'
          - 'request pfe execute target fpc0 command "test qsfp 10 laser on"'
        dest_dir: "{{playbook_dir}}/{{test_dir}}/"
      register: response
    - debug:
        var: response

    - name: sleep for 60 seconds and continue with play
      wait_for:
        timeout: 60

    - name: Checking interface status
      juniper_junos_command:
        command:
          - "show interfaces ae3 terse"
          - "show interfaces ae3 statistics"
        dest_dir: "{{playbook_dir}}/{{test_dir}}/"
      register: response
    - debug:
        var: response


