---
  - hosts: localhost:S-DC1-1
    gather_facts: no
    tasks:
    - set_fact: 
        testcase: 5-2-NF-CONVERG-EVI10-20-SRX-TYPE5
        test_dir: "testcase/5-2-NF-CONVERG-EVI10-20-SRX-TYPE5/1/UP"
        cacheable: yes
    
  - hosts: localhost
    gather_facts: no
    tasks:
    - file: 
        path: "{{playbook_dir}}/{{test_dir}}" 
        state: directory

  - name: Bringing up interface ae3 on S-DC1-1 (laser on)"
    hosts: S-DC1-1
    roles:
      - Juniper.junos
    connection: local
    gather_facts: no
    tasks:
    - name: Bringing up interface
      juniper_junos_command:
        command:
          - 'set cli timestamp'
          - 'request pfe execute target fpc0 command "test qsfp 10 laser on"'
        dest_dir: "{{playbook_dir}}/{{test_dir}}/"
      register: response
      
    - name: Print the coutput.
      debug:
        var: response