---
  - name: Retrieve Junos OS version from all devices
    hosts: DVT
    roles:
     - Juniper.junos
    connection: local
    gather_facts: no
    vars:
      junos_jinja_template: "{{playbook_dir}}/templates/spring-remove.j2"
      credentials:
        host: "{{ inventory_hostname }}"
        user: "{{ ansible_ssh_user }}"
        passwd: "{{ ansible_ssh_pass }}"
  
    tasks:

    #- name: Checking NETCONF connectivity
    #  wait_for: 
    #    host: "{{ inventory_hostname }}"
    #    port: "{{ ansible_port }}"
    #    timeout: 2
    #  register: netconf_result

    - name: Retrieve information from devices running Junos OS
      junos_get_facts:
      register: junos
   
    - name: Print the Junos OS version on RE0.
      debug:
        var: junos.version_RE0

    - name: Print the Junos OS version on RE1.
      debug:
        var: junos.version_RE1